//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Controllers_Customers_Form {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controllers_Customers_Form() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidlyPrototype.Resources.Controllers.Customers.Form", typeof(Controllers_Customers_Form).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer.
        /// </summary>
        public static string create_customer {
            get {
                return ResourceManager.GetString("create_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string date_of_birth {
            get {
                return ResourceManager.GetString("date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Rented.
        /// </summary>
        public static string date_rented {
            get {
                return ResourceManager.GetString("date_rented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Type.
        /// </summary>
        public static string membership_type {
            get {
                return ResourceManager.GetString("membership_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies Rented.
        /// </summary>
        public static string movies_rented {
            get {
                return ResourceManager.GetString("movies_rented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe To Newsletter?.
        /// </summary>
        public static string newsletter {
            get {
                return ResourceManager.GetString("newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter Subscription.
        /// </summary>
        public static string newsletter_sub {
            get {
                return ResourceManager.GetString("newsletter_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rentals Data Available.
        /// </summary>
        public static string no_rentals {
            get {
                return ResourceManager.GetString("no_rentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date(ERD).
        /// </summary>
        public static string return_date {
            get {
                return ResourceManager.GetString("return_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Membership Type.
        /// </summary>
        public static string select_mt {
            get {
                return ResourceManager.GetString("select_mt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customer.
        /// </summary>
        public static string update_customer {
            get {
                return ResourceManager.GetString("update_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Viewership Restricted.
        /// </summary>
        public static string viewership_restriction {
            get {
                return ResourceManager.GetString("viewership_restriction", resourceCulture);
            }
        }
    }
}
