//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Controller_Movies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controller_Movies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidlyPrototype.Resources.Controller.Movies", typeof(Controller_Movies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Movie.
        /// </summary>
        public static string add_movie {
            get {
                return ResourceManager.GetString("add_movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Added To Your Rentals List.
        /// </summary>
        public static string added_to_rentals {
            get {
                return ResourceManager.GetString("added_to_rentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string available {
            get {
                return ResourceManager.GetString("available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Movie.
        /// </summary>
        public static string create_movie {
            get {
                return ResourceManager.GetString("create_movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        public static string date_added {
            get {
                return ResourceManager.GetString("date_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Movie.
        /// </summary>
        public static string delete_movie {
            get {
                return ResourceManager.GetString("delete_movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a movie is chosen from the provided suggestion dropdown list, the movie id is stored and is used to acquire more data on the movie online. If you would like to input the movie details on your own, please make sure to input data without choosing from the dropdown list or if you choose from the list, please make sure to delete the entire movie name before inputing your own movie name..
        /// </summary>
        public static string form_info_message {
            get {
                return ResourceManager.GetString("form_info_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string genre {
            get {
                return ResourceManager.GetString("genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Genres.
        /// </summary>
        public static string movie_genres {
            get {
                return ResourceManager.GetString("movie_genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Movie Genre.
        /// </summary>
        public static string movie_genres_sl {
            get {
                return ResourceManager.GetString("movie_genres_sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number In Stock.
        /// </summary>
        public static string number_in_stock {
            get {
                return ResourceManager.GetString("number_in_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string page_title {
            get {
                return ResourceManager.GetString("page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string release_date {
            get {
                return ResourceManager.GetString("release_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string rent {
            get {
                return ResourceManager.GetString("rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to rent this movie?.
        /// </summary>
        public static string rent_sure {
            get {
                return ResourceManager.GetString("rent_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rented.
        /// </summary>
        public static string rented {
            get {
                return ResourceManager.GetString("rented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Movie.
        /// </summary>
        public static string update_movie {
            get {
                return ResourceManager.GetString("update_movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Movie Data.
        /// </summary>
        public static string view_movie {
            get {
                return ResourceManager.GetString("view_movie", resourceCulture);
            }
        }
    }
}
