//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Controller_Rentals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controller_Rentals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidlyPrototype.Resources.Controller.Rentals", typeof(Controller_Rentals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string customers {
            get {
                return ResourceManager.GetString("customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Rented.
        /// </summary>
        public static string date_rented {
            get {
                return ResourceManager.GetString("date_rented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform.
        /// </summary>
        public static string inform {
            get {
                return ResourceManager.GetString("inform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Notification To User That Rental Date is Almost Over.
        /// </summary>
        public static string inform_button_title {
            get {
                return ResourceManager.GetString("inform_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform Of Expiry.
        /// </summary>
        public static string inform_of_expiry {
            get {
                return ResourceManager.GetString("inform_of_expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform User of Movie Subscription Expiry Based on Return Date And Today&apos;s Date.
        /// </summary>
        public static string inform_title {
            get {
                return ResourceManager.GetString("inform_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnformed.
        /// </summary>
        public static string informed {
            get {
                return ResourceManager.GetString("informed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Name.
        /// </summary>
        public static string movie_name {
            get {
                return ResourceManager.GetString("movie_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentals.
        /// </summary>
        public static string rentals {
            get {
                return ResourceManager.GetString("rentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date[ERD].
        /// </summary>
        public static string return_date {
            get {
                return ResourceManager.GetString("return_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
    }
}
